version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app:consistent
      - node_modules:/home/node/app/node_modules:consistent
    networks:
      - app-network
    command: ./scripts/docker/wait-for.sh db:27017 -- ./node_modules/.bin/nodemon ./src/index.js

  db:
    image: mongo:4.2
    container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - database:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database:
  node_modules:
