version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    command: ./scripts/docker/wait-for.sh db:27017 -- ./node_modules/.bin/nodemon ./src/app.js

  db:
    image: mongo:4.4
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - database:/data/db
    networks:
      - app-network
    logging:
      driver: 'none'

networks:
  app-network:
    driver: bridge

volumes:
  database:
